import { type FormDataContentType } from './types';

export const DEFAULT_ERRORS = {
  unexpectedError: 'An unknown error occurred, trying again might help.',
  methodNotAllowed: 'Method not allowed.',
  notFound: 'Not found.',
  notImplemented: 'Not implemented.',
  invalidMediaType: 'Invalid media type.',
  operationNotAllowed: 'Operation not allowed.',
  invalidRequestBody: 'Invalid request body.',
  missingRequestBody: 'Missing request body.',
  invalidQueryParameters: 'Invalid query parameters.',
  invalidPathParameters: 'Invalid path parameters.'
};

export enum ValidMethod {
  GET = 'GET',
  PUT = 'PUT',
  POST = 'POST',
  DELETE = 'DELETE',
  OPTIONS = 'OPTIONS',
  HEAD = 'HEAD',
  PATCH = 'PATCH'
}

// Ignore: We don't want to use promises here to avoid making this an async function.
// eslint-disable-next-line @typescript-eslint/no-var-requires
export const VERSION = require('../package.json').version;

// eslint-disable-next-line @typescript-eslint/no-var-requires
export const HOMEPAGE = require('../package.json').homepage;

export const DEFAULT_TITLE = 'Next REST Framework';

export const DEFAULT_OG_TYPE = 'website';

export const DEFAULT_DESCRIPTION =
  'This is an autogenerated documentation by Next REST Framework.';

export const DEFAULT_FAVICON_URL =
  'https://raw.githubusercontent.com/blomqma/next-rest-framework/main/docs/static/img/favicon.ico';

export const DEFAULT_LOGO_URL =
  'https://raw.githubusercontent.com/blomqma/next-rest-framework/d02224b38d07ede85257b22ed50159a947681f99/packages/next-rest-framework/logo.svg';

export const FORM_DATA_CONTENT_TYPES_THAT_SUPPORT_VALIDATION: FormDataContentType[] =
  ['multipart/form-data', 'application/x-www-form-urlencoded'];
