import { merge } from 'lodash';
import { DEFAULT_FAVICON_URL, DEFAULT_LOGO_URL, VERSION } from '../constants';
import { type NextRestFrameworkConfig } from '../types';

export const DEFAULT_CONFIG: NextRestFrameworkConfig = {
  deniedPaths: [],
  allowedPaths: ['**'],
  openApiSpecOverrides: {
    info: {
      title: 'Next REST Framework',
      description:
        'This is an autogenerated OpenAPI spec by Next REST Framework.',
      version: `v${VERSION}`
    }
  },
  openApiJsonPath: '/openapi.json',
  autoGenerateOpenApiSpec: true,
  docsConfig: {
    provider: 'redoc',
    title: 'Next REST Framework | Docs',
    description:
      'This is an autogenerated OpenAPI spec by Next REST Framework.',
    faviconUrl: DEFAULT_FAVICON_URL,
    logoUrl: DEFAULT_LOGO_URL
  },
  suppressInfo: false,
  generatePathsTimeout: 5000
};

export const getConfig = (config?: NextRestFrameworkConfig) =>
  merge({}, DEFAULT_CONFIG, config);
