import { merge } from 'lodash';
import { OPEN_API_VERSION, VERSION } from '../constants';
import { logNextRestFrameworkError } from './logging';
import { type NextRestFrameworkConfig } from '../types';

export const DEFAULT_CONFIG = {
  openApiSpecOverrides: {
    openapi: OPEN_API_VERSION,
    info: {
      title: 'Next REST Framework',
      description:
        'This is an autogenerated OpenAPI spec by Next REST Framework.',
      version: VERSION
    },
    components: {}
  },
  openApiJsonPath: '/api/openapi.json',
  openApiYamlPath: '/api/openapi.yaml',
  swaggerUiPath: '/api',
  swaggerUiConfig: {
    title: 'Next REST Framework | SwaggerUI',
    description: 'Next REST Framework SwaggerUI',
    faviconHref:
      'https://raw.githubusercontent.com/blomqma/next-rest-framework/main/docs/static/img/favicon.ico',
    logoHref:
      'https://raw.githubusercontent.com/blomqma/next-rest-framework/d02224b38d07ede85257b22ed50159a947681f99/packages/next-rest-framework/logo.svg'
  },
  exposeOpenApiSpec: true,
  errorHandler: logNextRestFrameworkError,
  suppressInfo: false,
  generatePathsTimeout: 5000
};

export const getConfig = (config?: NextRestFrameworkConfig) =>
  merge({}, DEFAULT_CONFIG, config);
