import { OPEN_API_VERSION, VERSION } from '../constants';
import { OpenAPIV3_1 } from 'openapi-types';
import { Modify, NextRestFrameworkConfig } from '../types';
import { logNextRestFrameworkError } from './logging';

export const getDefaultConfig = ({
  config
}: {
  config?: NextRestFrameworkConfig;
} = {}): Modify<
  NextRestFrameworkConfig,
  {
    openApiSpecOverrides: OpenAPIV3_1.Document;
  }
> => ({
  openApiSpecOverrides: {
    openapi: OPEN_API_VERSION,
    info: {
      title: 'Next REST Framework',
      description:
        'This is an autogenerated OpenAPI spec by Next REST Framework.',
      version: VERSION
    },
    components: {}
  },
  openApiJsonPath: '/api/openapi.json',
  openApiYamlPath: '/api/openapi.yaml',
  swaggerUiPath: '/api',
  swaggerUiConfig: {
    title: 'Next REST Framework | SwaggerUI',
    description: 'Next REST Framework SwaggerUI',
    faviconHref:
      'https://raw.githubusercontent.com/blomqma/next-rest-framework/main/docs/static/img/favicon.ico',
    logoHref:
      'https://raw.githubusercontent.com/blomqma/next-rest-framework/d02224b38d07ede85257b22ed50159a947681f99/packages/next-rest-framework/logo.svg'
  },
  exposeOpenApiSpec: true,
  errorHandler: logNextRestFrameworkError,
  suppressInfo: false,
  apiRoutesPath: 'pages/api'
});
